# Generated by Django 4.2.2 on 2024-02-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='content',
        ),
        migrations.RemoveField(
            model_name='document',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(default=0, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
