# Generated by Django 4.2.2 on 2024-02-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_document_recipient_document_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='document',
            name='sender',
        ),
    ]
