# Generated by Django 4.2.2 on 2024-02-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0005_remove_document_recipient_remove_document_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
    ]
