# Generated by Django 4.2.2 on 2024-03-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0006_remove_document_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('remarks', models.FileField(upload_to='remarks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
