# Generated by Django 4.2.2 on 2024-03-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0007_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.FileField(upload_to='remarks/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='remarks',
            field=models.TextField(),
        ),
    ]
